### ISSUE TITLE
Content going out of page in mobile layout

### ISSUE THREAD

**Issue by Abhir-24** [dsc-jiit-128/Hacktoberfest_Exchange-Rate#12]
In the mobile layout, the contents of the page are going out of the page.

![Screenshot from 2020-09-27 19-01-29](https://user-images.githubusercontent.com/56101022/94366179-edb44780-00f3-11eb-881e-fcde96e4aa28.png)

**Comment by nitinshukla413** [comment]
Can you please assign this issue to me?

**Comment by Abhir-24** [comment]
yes go ahead but pls make the pull request in october only since PRs for hacktoberfest will be counted in october only and not before.
