### ISSUE TITLE
Input is not working

### ISSUE THREAD

**Issue by Abhir-24** [dsc-jiit-128/Hacktoberfest_Exchange-Rate#5]
In the 'amount-one' class the input is not being taken instead it is just showing a message printed in the console.

**Comment by janushi** [comment]
@Abhir-24 I would like to work on this issue. Can you assign me this?

**Comment by Abhir-24** [comment]
Hi @janushi , we are only accepting one participant for one particular issue. So please select only one issue which you want to work on, I will assign you that one.

**Comment by janushi** [comment]
Hi @Abhir-24 ,In that case I would like to work on **https://github.com/dsc-jiit-128/Hacktoberfest_Exchange-Rate/issues/9** this issue. Thanks.

**Comment by MuhammadTanveer94** [comment]
@Abhir-24 i want to do this could you please assign me?
