### ISSUE TITLE
Functionality not there in 'amount-one' class

### ISSUE THREAD

**Issue by Abhir-24** [dsc-jiit-128/Hacktoberfest_Exchange-Rate#7]
The 'amount-one' class should take input value and function like the other 'amount-two' class

**Comment by ayuushhh** [comment]
sir i want to work on this.As this is my first time please tell me which file i have to change?

**Comment by MuhammadTanveer94** [comment]
@Abhir-24 i want to do this, could you please assign me?

**Comment by Abhir-24** [comment]
ya sure, go ahead
