### ISSUE TITLE
No space in between elements

### ISSUE THREAD

**Issue by Abhir-24** [dsc-jiit-128/Hacktoberfest_Exchange-Rate#9]
There is very less space between the swap button and the option list.

![Screenshot from 2020-09-27 18-48-39](https://user-images.githubusercontent.com/56101022/94365890-24895e00-00f2-11eb-8081-00bb6566a57c.png)

It should have space like this.

![Screenshot from 2020-09-27 18-49-56](https://user-images.githubusercontent.com/56101022/94365914-47b40d80-00f2-11eb-98bd-4478df2a219a.png)

**Comment by janushi** [comment]
@Abhir-24 I would like to work on this issue. Can you assign me this?

**Comment by janushi** [comment]
Hi @Abhir-24 , I would like to go for this issue. Please assign me this issue.
